server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false  # Set to true in production with HTTPS
        http-only: true

spring:
  profiles:
    active: springai
  application:
    name: agent-workshop-assignments
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        sse:
          connections:
            location-mcp:
              url: http://localhost:8081
              sse-endpoint: /sse
  autoconfigure:
    exclude:
      - org.springframework.ai.mcp.client.autoconfigure.SseWebFluxTransportAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          web-app:
            provider: web-app
            client-id: web-app-client
            client-secret: web-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/web-app"
            scope: [ openid, profile, email, favourites.read, favourites.write ]
            client-name: "Agent Web App Client"
          favourites-mcp:
            provider: auth-server
            client-id: favourites-mcp
            client-secret: mcp-secret
            authorization-grant-type: client_credentials
            scope: [ mcp.invoke ]
            client-name: "Favourites MCP Client"
        provider:
          web-app:
            issuer-uri: http://auth-server:9000
            user-name-attribute: sub
          auth-server:
            token-uri: http://auth-server:9000/oauth2/token
            user-name-attribute: sub


openai:
  proxy:
    url: https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3R1ZGVudCIsImRlc2NyaXB0aW9uIjoid29ya3Nob3AiLCJpYXQiOjE3NTk2NzgwMDMsImV4cCI6MTc1OTY4ODgwM30.w1AxbB9rLn63cSYEf0hmmEQRDsyWMQpSYdXktXHnYuQ

logging:
  level:
    root: INFO
    org.rag4j.agent: INFO
    org.springframework.ai: INFO


agent:
  plain:
    reasoning:
      max-reasoning-steps: 5
    memory:
      max-conversation-size: 10
