spring:
  profiles:
    active: plain
  application:
    name: agent-workshop-assignments


openai:
  proxy:
    url: https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3R1ZGVudCIsImRlc2NyaXB0aW9uIjoid29ya3Nob3AiLCJpYXQiOjE3NTk0MjYwNzgsImV4cCI6MTc1OTQzNjg3OH0.RhmRuuOyMq7flGadtB8bFnSznLvEXsgtKg7hchTI4E0

logging:
  level:
    root: INFO
    org.rag4j.agent: INFO
    org.springframework.ai: INFO


agent:
  plain:
    reasoning:
      max-reasoning-steps: 5
    memory:
      max-conversation-size: 10
