spring:
  profiles:
    active: springai-multi
  application:
    name: agent-workshop-assignments


openai:
  proxy:
    url: https://vfjv12h3xb.execute-api.eu-west-1.amazonaws.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic3R1ZGVudCIsImRlc2NyaXB0aW9uIjoid29ya3Nob3AiLCJpYXQiOjE3NTk1MDcwNDUsImV4cCI6MTc1OTUxNzg0NX0.TraiV-M_rlPDqEw-2Vi2v-9Mst41e1aGqQdkWKms1DQ

logging:
  level:
    root: INFO
    org.rag4j.agent: INFO
    org.springframework.ai: INFO


agent:
  plain:
    reasoning:
      max-reasoning-steps: 5
    memory:
      max-conversation-size: 10
